language: ruby
sudo: false
cache: bundler
script: travis_wait bundle exec rake generate
after_success:
- '[ "${TRAVIS_BRANCH}" = "current" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake deploy || false'
